---
title: "Group_project_draft"
author: "Cody.ke"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## R Markdown
The R Markdown file should include a section in which you read in the raw data files and transform the data for analysis. Exclude this R code from the knitted HTML report by using include=FALSE in the corresponding R chunks.
Your data analysis should include data exploration including graphical and numerical summaries which do not appear in the final report. You may exclude such analysis by using include=FALSE in the corresponding R chunks.
The methods of analysis should primarily be methods discussed from the course.
Data
Upload one or more data files that can be read in with code in the R Markdown file to replicate your analysis.
R Markdown
The instructors should be able to knit your document if the file and all of the data files are in the same directory.
HTML Full Report
The knitted HTML document should contain the following sections. There is no limit on the overall length of this document, but the aim is to introduce your question(s) and describe your results concisely and persuasively.

The knitted document should not include any of the code used for the analysis or graphics. (Set echo=FALSE to suppress the code or include=FALSE to suppress both code and output in the R chunks as appropriate.)

Your report should include the following sections.

Introduction
The opening sentence or sentences should draw the reader into your report by providing high-level motivation for the analysis. 
Describe the question or questions of interest and the motivation for the analysis.
Conclude the introduction with a thesis statement.
A thesis statement comprises one or two declarative sentences that summarize the main point of the report and clearly makes an assertion and communicates to the reader the position the authors have taken on the topic.1Links to an external site.
Background
Describe the data set, how it was collected, what the variables mean.
Cite the source of your data.
Describe any background information needed to better comprehend the question or questions you are posing and how the data relate to the question.
Describe any unusual factors which may affect interpretation of results.
Describe what you intend to do in the rest of the report.
Analysis
Include numerical and graphical summaries of the data. Be sure to introduce and describe your numerical and graphical summaries.  Do not display a series of summaries without text explaining them.
Make sure to include at least one graphical display of the data that best supports your main conclusions for your primary question, and explain how it supports your conclusions.
For each inference you make, briefly describe the method you use and what the results are.
Provide evidence to support each of your claims.
This section should not include substantial interpretation of results. Leave that for the discussion.
Discussion
Provide broader interpretations of your analysis and describe how to interpret your results with respect to your question of interest.
Discuss any potential short-comings of the analysis.
Discuss potential future directions for additional work
New questions
Different methods to address the same questions
New data you might collect to refine your understanding
Summarize your primary conclusions and the primary evidence that supports these conclusions.
References
In the R Markdown file, you may automatically cite other resources by using a caret followed by the reference between square brackets: ^[your reference text] which will place a marker at this location and a footnote at the end of the document.

